fail_fast: false

repos:
  # Standard hooks for things like trailing whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      # - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: claude-plugin-validate
        name: claude plugin validate
        entry: claude plugin validate .
        language: system
        pass_filenames: false
        files: (plugin\.json|marketplace\.json|SKILL\.md|\.md)$

  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        exclude: ^.*/(agents|skills)/
        additional_dependencies:
          - mdformat-gfm
          - mdformat-footnote==0.1.1
          - mdformat-config
          - mdformat-ruff
          - mdformat-toc
